<?php

return [
    'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'laravel_ai_crm'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'options' => [
                \PDO::ATTR_CASE => \PDO::CASE_NATURAL,
                \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
                \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC,
                \PDO::ATTR_EMULATE_PREPARES => false,
            ],
        ],
        'mongodb' => [
            'driver' => 'mongodb',
            'host' => env('MONGO_HOST', '127.0.0.1'),
            'port' => env('MONGO_PORT', 27017),
            'database' => env('MONGO_DATABASE', 'laravel_ai_crm'),
            'username' => env('MONGO_USERNAME', ''),
            'password' => env('MONGO_PASSWORD', ''),
            'options' => [
                'database' => env('MONGO_DB_DATABASE', 'admin'),
                'username' => env('MONGO_DB_USERNAME', 'admin'),
                'password' => env('MONGO_DB_PASSWORD', 'password'),
                'authSource' => env('MONGO_DB_AUTH_SOURCE', 'admin'),
                'replicaSet' => env('MONGO_DB_REPLICA_SET', 'rs0'),
                'readPreference' => 'secondary',
                'wtimeoutMS' => 5000,
                'w' => 1,
                'j' => false,
                'readConcern' => 'local',
                'serverSelectionTimeoutMS' => 30000,
                'heartbeatFrequencyMS' => 10000,
                'maxIdleTimeMS' => 0,
                'maxLifeTimeMS' => 0,
                'connectTimeoutMS' => 10000,
                'socketTimeoutMS' => 0,
                'uuidRepresentation' => 'standard',
                'serverSelectionTimeoutMS' => 30000,
                'heartbeatFrequencyMS' => 10000,
                'maxIdleTimeMS' => 0,
                'maxLifeTimeMS' => 0,
                'connectTimeoutMS' => 10000,
                'socketTimeoutMS' => 0,
                'uuidRepresentation' => 'standard',
            ],
        ],
    ],
    'mongodb' => [
        'client' => [
            'driver' => 'mongodb',
            'host' => env('MONGO_HOST', '127.0.0.1'),
            'port' => env('MONGO_PORT', 27017),
            'database' => env('MONGO_DATABASE', 'laravel_ai_crm'),
            'username' => env('MONGO_USERNAME', ''),
            'password' => env('MONGO_PASSWORD', ''),
            'options' => [
                'database' => env('MONGO_DB_DATABASE', 'admin'),
                'username' => env('MONGO_DB_USERNAME', 'admin'),
                'password' => env('MONGO_DB_PASSWORD', 'password'),
                'authSource' => env('MONGO_DB_AUTH_SOURCE', 'admin'),
                'replicaSet' => env('MONGO_DB_REPLICA_SET', 'rs0'),
                'readPreference' => 'secondary',
                'wtimeoutMS' => 5000,
                'w' => 1,
                'j' => false,
                'readConcern' => 'local',
                'serverSelectionTimeoutMS' => 30000,
                'heartbeatFrequencyMS' => 10000,
                'maxIdleTimeMS' => 0,
                'maxLifeTimeMS' => 0,
                'connectTimeoutMS' => 10000,
                'socketTimeoutMS' => 0,
                'uuidRepresentation' => 'standard',
                'serverSelectionTimeoutMS' => 30000,
                'heartbeatFrequencyMS' => 10000,
                'maxIdleTimeMS' => 0,
                'maxLifeTimeMS' => 0,
                'connectTimeoutMS' => 10000,
                'socketTimeoutMS' => 0,
                'uuidRepresentation' => 'standard',
            ],
        ],
    ],
];